const { domain } = require('../config');

module.exports = {
	"Actions": `${domain}/Actions.aspx`,
	"Activities": `${domain}/Activities.aspx`,
	"Ancestries": `${domain}/Ancestries.aspx`,
	"AnimalCompanions": `${domain}/AnimalCompanions.aspx`,
	"AnimalSpecializations": `${domain}/AnimalCompanions.aspx?Specialized=true`,
	"Archetypes": `${domain}/Archetypes.aspx`,
	"ArcaneSchools": `${domain}/ArcaneSchools.aspx`,
	"ArcaneThesis": `${domain}/ArcaneThesis.aspx`,
	"Armor": `${domain}/Armor.aspx`,
	"Backgrounds": `${domain}/Backgrounds.aspx`,
	"Bloodlines": `${domain}/Bloodlines.aspx`,
	"Causes": `${domain}/Causes.aspx`,
	"Classes": `${domain}/Classes.aspx`,
	"ClassKits": `${domain}/ClassKits.aspx`,
	"ClassSamples": `${domain}/ClassSamples.aspx`,
	"Conditions": `${domain}/Conditions.aspx`,
	"Deities": `${domain}/Deities.aspx`,
	"Doctrines": `${domain}/Doctrines.aspx`,
	"Domains": `${domain}/Domains.aspx`,
	"DruidicOrders": `${domain}/DruidicOrders.aspx`,
	"Equipment": `${domain}/Equipment.aspx`,
	"Familiars": `${domain}/Familiars.aspx`,
	"Feats": `${domain}/Feats.aspx`,
	"Hazards": `${domain}/Hazards.aspx`,
	"HuntersEdge": `${domain}/HuntersEdge.aspx`,
	"Instincts": `${domain}/Instincts.aspx`,
	"Languages": `${domain}/Languages.aspx`,
	"Monsters": `${domain}/Monsters.aspx`,
	"MonsterAbilities": `${domain}/MonsterAbilities.aspx`,
	"MonsterFamilies": `${domain}/MonsterFamilies.aspx`,
	"Muses": `${domain}/Muses.aspx`,
	"Rackets": `${domain}/Rackets.aspx`,
	"ResearchFields": `${domain}/ResearchFields.aspx`,
	"Rules": `${domain}/Rules.aspx`,
	"Setting": `${domain}/Setting.aspx`,
	"Shields": `${domain}/Shields.aspx`,
	"Skills": `${domain}/Skills.aspx`,
	"Spells": `${domain}/Spells.aspx`,
	"Rituals": `${domain}/Rituals.aspx`,
	"Tenets": `${domain}/Tenets.aspx`,
	"Traits": `${domain}/Traits.aspx`,
	"Weapons": `${domain}/Weapons.aspx`,
	"WeaponGroups": `${domain}/WeaponGroups.aspx`
}
