flowchart LR
  %% htmlPageDAG:aonprd (v2.0)
  html:fetch
  html:fetch[html:fetch]
  html:fetch -->|success| aonprd:parse
  html:fetch -->|cached| aonprd:parse
  html:fetch -->|error| htmlPage:failed
  aonprd:parse[[aonprd:parse]]
  aonprd:parse -->|success| json:write
  aonprd:parse -->|error| htmlPage:failed
  json:write[json:write]
  json:write -->|success| htmlPage:completed
  json:write -->|skipped| htmlPage:completed
  htmlPage:completed(((htmlPage:completed\n(completed))))
  htmlPage:failed>htmlPage:failed\n(failed)]