flowchart LR
  %% htmlScrapeDAGCrawl (v2.0)
  crawl
  crawl[[crawl]]
  crawl -->|success| scrape
  crawl -->|error| scrape-done
  scrape[[scrape]]
  scrape -->|success| retry
  scrape -->|error| retry
  retry[[retry]]
  retry -->|success| scrape-done
  retry -->|error| scrape-done
  scrape-done(((scrape-done\n(completed))))