flowchart LR
  %% htmlScrapeDAG (v2.0)
  scrape
  scrape([scrape])
  scrape -->|success| retry
  scrape -->|error| retry
  retry([retry])
  retry -->|success| done
  retry -->|error| done
  done[done]
  done -->|success| END
  END([end])