flowchart LR
  %% wikiRetryPhase (v2.0)
  retry-titles
  retry-titles{{retry-titles}}
  retry-titles -->|all-success| END
  retry-titles -->|partial| END
  retry-titles -->|all-error| END
  retry-titles -->|empty| END
  END([end])