flowchart LR
  %% wikiScrapeDAG (v2.0)
  scrape
  scrape[[scrape]]
  scrape -->|success| retry
  scrape -->|error| retry
  retry[[retry]]
  retry -->|success| scrape-done
  retry -->|error| scrape-done
  scrape-done(((scrape-done\n(completed))))