flowchart LR
  %% wiki-docs:parse (v2.0)
  wiki-docs:parse-impl
  wiki-docs:parse-impl[wiki-docs:parse-impl]
  wiki-docs:parse-impl -->|success| wiki-docs:parse:done
  wiki-docs:parse:done(((wiki-docs:parse:done\n(completed))))