module.exports = {
	"debug": true,
	"domain": "http://2e.aonprd.com",
	"target": /\?ID=/,
	"reportDirectory": "reports",
	"dataDirectory": "data",
	"delayTimer": 50,
	"categories": [
		"Actions",
		"Activities",
		"Ancestries",
		"AnimalCompanions",
		"Archetypes",
		"ArcaneSchools",
		"ArcaneThesis",
		"Armor",
		"Backgrounds",
		"Bloodlines",
		"Causes",
		"Classes",
		"ClassKits",
		"Conditions",
		"Deities",
		"Doctrines",
		"Domains",
		"DruidicOrders",
		"Equipment",
		"Familiars",
		"Feats",
		"Hazards",
		"HuntersEdge",
		"Instincts",
		"Languages",
		"Monsters",
		"MonsterAbilities",
		"MonsterFamilies",
		"Muses",
		"Rackets",
		"ResearchFields",
		"Rules",
		"Setting",
		"Shields",
		"Skills",
		"Spells",
		"Rituals",
		"Tenets",
		"Traits",
		"Weapons",
		"WeaponGroups"
	]
};
